// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: esp_rmaker_chal_resp.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum RmakerMisc_RMakerMiscStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case success // = 0
  case fail // = 1
  case invalidParam // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .success
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .success
    case 1: self = .fail
    case 2: self = .invalidParam
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .success: return 0
    case .fail: return 1
    case .invalidParam: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RmakerMisc_RMakerMiscStatus] = [
    .success,
    .fail,
    .invalidParam,
  ]

}

enum RmakerMisc_RMakerMiscMsgType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case typeCmdChallengeResponse // = 0
  case typeRespChallengeResponse // = 1
  case typeCmdGetNodeID // = 2
  case typeRespGetNodeID // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .typeCmdChallengeResponse
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .typeCmdChallengeResponse
    case 1: self = .typeRespChallengeResponse
    case 2: self = .typeCmdGetNodeID
    case 3: self = .typeRespGetNodeID
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .typeCmdChallengeResponse: return 0
    case .typeRespChallengeResponse: return 1
    case .typeCmdGetNodeID: return 2
    case .typeRespGetNodeID: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RmakerMisc_RMakerMiscMsgType] = [
    .typeCmdChallengeResponse,
    .typeRespChallengeResponse,
    .typeCmdGetNodeID,
    .typeRespGetNodeID,
  ]

}

struct RmakerMisc_CmdCRPayload: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payload: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RmakerMisc_RespCRPayload: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payload: Data = Data()

  var nodeID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Empty payload 
struct RmakerMisc_CmdGetNodeIDPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RmakerMisc_RespGetNodeIDPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var nodeID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct RmakerMisc_RMakerMiscPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var msg: RmakerMisc_RMakerMiscMsgType = .typeCmdChallengeResponse

  var status: RmakerMisc_RMakerMiscStatus = .success

  var payload: RmakerMisc_RMakerMiscPayload.OneOf_Payload? = nil

  var cmdChallengeResponsePayload: RmakerMisc_CmdCRPayload {
    get {
      if case .cmdChallengeResponsePayload(let v)? = payload {return v}
      return RmakerMisc_CmdCRPayload()
    }
    set {payload = .cmdChallengeResponsePayload(newValue)}
  }

  var respChallengeResponsePayload: RmakerMisc_RespCRPayload {
    get {
      if case .respChallengeResponsePayload(let v)? = payload {return v}
      return RmakerMisc_RespCRPayload()
    }
    set {payload = .respChallengeResponsePayload(newValue)}
  }

  var cmdGetNodeIdpayload: RmakerMisc_CmdGetNodeIDPayload {
    get {
      if case .cmdGetNodeIdpayload(let v)? = payload {return v}
      return RmakerMisc_CmdGetNodeIDPayload()
    }
    set {payload = .cmdGetNodeIdpayload(newValue)}
  }

  var respGetNodeIdpayload: RmakerMisc_RespGetNodeIDPayload {
    get {
      if case .respGetNodeIdpayload(let v)? = payload {return v}
      return RmakerMisc_RespGetNodeIDPayload()
    }
    set {payload = .respGetNodeIdpayload(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case cmdChallengeResponsePayload(RmakerMisc_CmdCRPayload)
    case respChallengeResponsePayload(RmakerMisc_RespCRPayload)
    case cmdGetNodeIdpayload(RmakerMisc_CmdGetNodeIDPayload)
    case respGetNodeIdpayload(RmakerMisc_RespGetNodeIDPayload)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rmaker_misc"

extension RmakerMisc_RMakerMiscStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Success"),
    1: .same(proto: "Fail"),
    2: .same(proto: "InvalidParam"),
  ]
}

extension RmakerMisc_RMakerMiscMsgType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "TypeCmdChallengeResponse"),
    1: .same(proto: "TypeRespChallengeResponse"),
    2: .same(proto: "TypeCmdGetNodeID"),
    3: .same(proto: "TypeRespGetNodeID"),
  ]
}

extension RmakerMisc_CmdCRPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CmdCRPayload"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "payload"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerMisc_CmdCRPayload, rhs: RmakerMisc_CmdCRPayload) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerMisc_RespCRPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RespCRPayload"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "payload"),
    2: .standard(proto: "node_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nodeID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 1)
    }
    if !self.nodeID.isEmpty {
      try visitor.visitSingularStringField(value: self.nodeID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerMisc_RespCRPayload, rhs: RmakerMisc_RespCRPayload) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.nodeID != rhs.nodeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerMisc_CmdGetNodeIDPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CmdGetNodeIDPayload"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerMisc_CmdGetNodeIDPayload, rhs: RmakerMisc_CmdGetNodeIDPayload) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerMisc_RespGetNodeIDPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RespGetNodeIDPayload"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "node_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.nodeID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.nodeID.isEmpty {
      try visitor.visitSingularStringField(value: self.nodeID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerMisc_RespGetNodeIDPayload, rhs: RmakerMisc_RespGetNodeIDPayload) -> Bool {
    if lhs.nodeID != rhs.nodeID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerMisc_RMakerMiscPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RMakerMiscPayload"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "msg"),
    2: .same(proto: "status"),
    10: .same(proto: "cmdChallengeResponsePayload"),
    11: .same(proto: "respChallengeResponsePayload"),
    12: .same(proto: "cmdGetNodeIDPayload"),
    13: .same(proto: "respGetNodeIDPayload"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.msg) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 10: try {
        var v: RmakerMisc_CmdCRPayload?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .cmdChallengeResponsePayload(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .cmdChallengeResponsePayload(v)
        }
      }()
      case 11: try {
        var v: RmakerMisc_RespCRPayload?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .respChallengeResponsePayload(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .respChallengeResponsePayload(v)
        }
      }()
      case 12: try {
        var v: RmakerMisc_CmdGetNodeIDPayload?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .cmdGetNodeIdpayload(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .cmdGetNodeIdpayload(v)
        }
      }()
      case 13: try {
        var v: RmakerMisc_RespGetNodeIDPayload?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .respGetNodeIdpayload(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .respGetNodeIdpayload(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.msg != .typeCmdChallengeResponse {
      try visitor.visitSingularEnumField(value: self.msg, fieldNumber: 1)
    }
    if self.status != .success {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    switch self.payload {
    case .cmdChallengeResponsePayload?: try {
      guard case .cmdChallengeResponsePayload(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .respChallengeResponsePayload?: try {
      guard case .respChallengeResponsePayload(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .cmdGetNodeIdpayload?: try {
      guard case .cmdGetNodeIdpayload(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .respGetNodeIdpayload?: try {
      guard case .respGetNodeIdpayload(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerMisc_RMakerMiscPayload, rhs: RmakerMisc_RMakerMiscPayload) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.status != rhs.status {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
